# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lcpa_cpp <- function(x, y, logfile, R_max = 3L, time_limit = 60L) {
    .Call(`_riskslimr_lcpa_cpp`, x, y, logfile, R_max, time_limit)
}

lcpa_glpk <- function(x, y, R_max = 3L, time_limit = 60L) {
    .Call(`_riskslimr_lcpa_glpk`, x, y, R_max, time_limit)
}

compute_loss <- function(lambda, x, y) {
    .Call(`_riskslimr_compute_loss`, lambda, x, y)
}

compute_loss_grad <- function(lambda, x, y) {
    .Call(`_riskslimr_compute_loss_grad`, lambda, x, y)
}

